### ISSUE TITLE
[9.4.18] [1.12.2] Digital Miner Not working

### ISSUE THREAD

**Issue by aking4125** [dizzyd/Mekanism#32] opened 2019-03-09 14:47 UTC
#### Steps to reproduce:
1. Place down Digital Miner
2. Give it power and configure it to mine anything
3. Doesn't work. Takes power away, resets counter to zero and does nothing.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2815
**Mekanism: DZ Edition 9.4.18
**Other relevant version: On a private server. Potential mod conflict somewhere?

#### If a (crash)log is relevant for this issue, link it here: Should I post the server log or client log?

**Comment by dizzyd** [comment] 2019-03-09 15:31
Hi @aking4125 - thanks for the bug report. I can't say I've seen this behaviour on my private modpack, so I'm guessing your suspicion about cross-mod interaction is correct. 

Could you please provide:
1. Screenshot of your Digital Miner and how you're powering it and configuring it
2. The manifest.json file from your modpack

In addition, did this same setup work when you weren't using the DZ edition of Mekanism?

Thanks!

**Comment by aking4125** [comment] 2019-03-09 15:45
Yeah. Here is the screen shots. And no we haven't used the original version. Started from DZ IIRC. At least I don't think we did.

https://ibb.co/tqkMbH4 = It's receiving power from a reactor from Extreme Reactors using the quantum entangloporter

https://ibb.co/hf6R96g = Opening the GUI, I configured it to mine *ore*. This is what you'll see before I click start. It reads everything is a go.

https://ibb.co/bm20byP = Once I click start. You can see it found the ores within range. One second later, it'll show the next picture. The power bar drops for a mircosecond (Too hard for me to capture currently)

https://ibb.co/GM495z2 = One second after I clicked start. The amount of ores within range reverts to zero. Nothing is collected in the Inventory below or any connected inventories. 

We crafted it in survival. I then used creative here to spawn another one in. Same issues. With or without upgrades, range set to anything, filters set to anything. The digital Miner just doesn't work.

As for the manifest.json. I'm confused on this. I found only the one file which is related to draconic evolution https://pastebin.com/FrQD8iZZ

**Comment by dizzyd** [comment] 2019-03-09 16:00
Hmm, this is a perplexing one. It doesn't look like it's running out of power, based on the screenshots. 

Are you using a custom mod pack? Can you provide a list of mods and versions? (The manifest.json is a file used by Curse/Twitch when assembling a modpack - if you did something by hand you might not have one)

**Comment by aking4125** [comment] 2019-03-09 16:14
I didn't use Curse/Twitch. I created the pack manually using the Vanilla Launcher.

And is there an easy way to just, print a mod list? There's a bunch here (Over 260)

**Comment by dizzyd** [comment] 2019-03-09 16:26
You can provide a directory listing of the mods/ directory. However, if that's what you're doing, mat I suggest that you create a testing mod pack and copy over only MDZ and see if you have the problem with _just_ that? 260 mods would be a lot for me to work through by myself. :)

**Comment by aking4125** [comment] 2019-03-09 16:37
I'm gonna try the original version of Mekanism and see if that works.

Edit: The original version works, and the DZ via single player. It's just the server or this world at least....Hmm...

**Comment by dizzyd** [comment] 2019-03-10 00:04
@aking4125 - I suspect it's a mod interaction, but without further data it's really hard to narrow down. I've verified that the DM works as expected in both server and client environments with a smallish set of mods (~100). If you want to start doing a process of elimination with your specific modpack, I'd focus first on MDZ in conjunction with any mods that generate ore and then expand from there.

I'm going to close this issue for now, since we can't reproduce except in your specific environment. Please feel free to reopen if you are able to find a specific mod interaction that doesn't work -- we want those bugs SQUASHED. :)

**Closed as completed by dizzyd** 2019-03-10 00:04 UTC
Labels: question

**Comment by aking4125** [comment] 2019-03-10 14:09
Any mod that spawns ore....Hmm. I'll look into it for sure. I'll come back if I find anything.

**Comment by aking4125** [comment] 2019-03-10 20:02
I can't find the reason for it but starting a new world on the server fixes the miner. So it's something within the world itself. Very odd.
